theme = "awesome-identity"
baseURL = "https://jean-michel.lehker.net"
title = "Jean-Michel Lehker"


## Profile Configurations
[params.profile]
  portrait = "images/portrait.png"
  firstname = "Jean-Michel"
  lastname = "Lehker"
  title = "Software Engineer"
  bio = """Full-stack developer with over a decade of industry experience in software development.
  """

## Contacts Configurations
[params.contacts]
  email = "jean-michel@lehker.net"
  github = "jlehker"
  linkedin = "jmlehker"

## Footer Configurations
[params.footer]
  copyright = "© 2021 Jean-Michel Lehker. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false
