theme = "awesome-identity"
baseURL = "https://jean-michel.lehker.net"
title = "Awesome Identity for Jean-Michel Lehker"


## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Jean-Michel"
  lastname = "Lehker"
  title = "Software Engineer"
  bio = """Full-stack developer with over 10 years experience in Python development. leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.

  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
  """


## Footer Configurations
[params.footer]
  poweredBy = false
